# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_valves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 8, 8, 34, 150762)),
        ),
    ]
