# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_valves', '0003_auto_20170324_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='A title', max_length=100),
            preserve_default=False,
        ),
    ]
